apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: set-admin-cluster
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: server_url
            value: "{{inputs.parameters.server_url}}"
          - name: target_realm_name
            value: "{{inputs.parameters.target_realm_name}}"
          - name: target_client_id
            value: "{{inputs.parameters.target_client_id}}"
          - name: keycloak_credential_secret_name
            value: "{{inputs.parameters.keycloak_credential_secret_name}}"
          - name: keycloak_credential_secret_namespace
            value: "{{inputs.parameters.keycloak_credential_secret_namespace}}"
          - name: client_role_name
            value: "{{inputs.parameters.client_role_name}}"
          - name: user_names
            value: "{{inputs.parameters.user_names}}"
      steps:
        - - name: create-client
            templateRef:
              name: keycloak-client
              template: create-client
            arguments:
              parameters:
                - name: server_url
                  value: "{{inputs.parameters.server_url}}"
                - name: target_realm_name
                  value: "{{inputs.parameters.target_realm_name}}"
                - name: target_client_id
                  value: "{{inputs.parameters.target_client_id}}"
                - name: keycloak_credential_secret_name
                  value: "{{inputs.parameters.keycloak_credential_secret_name}}"
                - name: keycloak_credential_secret_namespace
                  value: "{{inputs.parameters.keycloak_credential_secret_namespace}}"
        - - name: create-client-role
            templateRef:
              name: keycloak-client
              template: create-client-role
            arguments:
              parameters:
                - name: server_url
                  value: "{{inputs.parameters.server_url}}"
                - name: target_realm_name
                  value: "{{inputs.parameters.target_realm_name}}"
                - name: target_client_id
                  value: "{{inputs.parameters.target_client_id}}"
                - name: keycloak_credential_secret_name
                  value: "{{inputs.parameters.keycloak_credential_secret_name}}"
                - name: keycloak_credential_secret_namespace
                  value: "{{inputs.parameters.keycloak_credential_secret_namespace}}"
                - name: client_role_name
                  value: "{{inputs.parameters.client_role_name}}"
        - - name: create-client-scope-mapper-client-role
            templateRef:
              name: keycloak-client
              template: create-client-scope-mapper-client-role
            arguments:
              parameters:
                - name: server_url
                  value: "{{inputs.parameters.server_url}}"
                - name: target_realm_name
                  value: "{{inputs.parameters.target_realm_name}}"
                - name: target_client_id
                  value: "{{inputs.parameters.target_client_id}}"
                - name: keycloak_credential_secret_name
                  value: "{{inputs.parameters.keycloak_credential_secret_name}}"
                - name: keycloak_credential_secret_namespace
                  value: "{{inputs.parameters.keycloak_credential_secret_namespace}}"
                - name: mapper_name
                  value: k8s-role-mapper
                - name: claim_name
                  value: groups
                - name: add_to_access_token
                  value: false
                - name: add_to_id_token
                  value: true
                - name: add_to_userinfo
                  value: false
        - - name: assign-client-role-to-user
            templateRef:
              name: keycloak-user
              template: assign-client-role-to-user
            arguments:
              parameters:
                - name: server_url
                  value: "{{inputs.parameters.server_url}}"
                - name: target_realm_name
                  value: "{{inputs.parameters.target_realm_name}}"
                - name: target_client_id
                  value: "{{inputs.parameters.target_client_id}}"
                - name: keycloak_credential_secret_name
                  value: "{{inputs.parameters.keycloak_credential_secret_name}}"
                - name: keycloak_credential_secret_namespace
                  value: "{{inputs.parameters.keycloak_credential_secret_namespace}}"
                - name: client_role_name
                  value: "{{inputs.parameters.client_role_name}}"
                - name: user_names
                  value: "{{inputs.parameters.user_names}}"
